name: Run Semgrep on Push

on:
  push:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    env:
        SEMGREP_APP_TOKEN : ${{ secrets.SEMGREP_APP_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (Semgrep requires it)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

     
      - name: Run Semgrep CI scan
        run: semgrep ci

    